### ISSUE TITLE
Active To-do List

### ISSUE THREAD

**Issue by newm-newm** [john-salman/project_1#6]
- [x] Task 1
     - [x] Scatter plots
- [x] Task 2
     - [x] Generate fibonacci sequence using iterative algorithm
     - [x] Compute GCD where m = F(k+1) and n = F(k) for several values of k >= 1.
     - [x] What should be the upper bound of k? (Clearly indicate in report)
     - [x] How does your analysis change if instead of measuring number of modulo divisions, you measure the actual time taken by the program to output the result?
     - [x] Produce a scatterplot showing the number of modulo divisions taken to compute GCD as function of m
     - [x] Indicate the algorithms likely worst-case efficiency class.
- [ ] Task 3
     - [x] Implement sieve of Eratosthenes to generate array of prime numbers and ascertain efficiency class.
     - [ ] Generate scatter-plot
     - [x] Design and implement an algorithm to find all the common elements in two sorted lists A and B of numbers (not necessarily prime numbers). make sure it runs in theta(n) (where n = max size of A and B).
     - [ ] Demonstrate its theta(n) complexity.
- [ ] Report
     - [x] task 1
     - [x] task 2
     - [ ] task 3
- [x] Read-Me
     - [x] Sample output for each program
     - [x] Basic premise of programs
- [x] Makefile or similar "Build-All" device
